---
title: Data ETL for WA+ Dashboard
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data ETL for WA+ Dashboard}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Overview

This repository contains server and client codes for a Water Accounting+ visualization dashboard. All codes and assets are provided as a standard R package. The dashboard application itself is written in R and uses the open-source [R/Shiny](https://shiny.rstudio.com/) framework.

The dashboard uses output from IWMI WA+ hydrological models, with the main code routine documented at [WAPORWA](https://github.com/wateraccounting/WAPORWA) (WaPOR-based Water Accounting).

Two hydrological basin are provided in the initial release, the **lower Niger River** in Mali and **Mara River** in Kenya. There are differences between the two use cases, in terms of data availability and temporal scope (e.g. in Mali only a subset of the entire WAPORWA model was obtained), meaning the level of details available through the dashboard will vary according to each river basin.



# Technical Guide

## Repository Structure

The repo is structured as a standard R package, in particular:

- `/data-raw`: configuration files
- `/inst`: client and server scripts and web assets for the Shiny application
- `/R`: all custom R functions
- `/docs`: rendered HTML documentation

Inside RStudio IDE the application can be previewed in a browser with `source("app.R")`.

Shell scripts are provided to automate common tasks: 

- `/build.sh`: rebuild and install the package for testing
- `/pkgdown.sh`: rebuild HTML package documentation (uses [pkgdown](https://pkgdown.r-lib.org/) framework)
- `/deploy.sh`: commit release to Github, rebuild Docker image, and deploy image to AWS ECR


## Data ETL


## Extend, Build, and Deploy


